// <auto-generated />
namespace testProduct.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class cofig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cofig));
        
        string IMigrationMetadata.Id
        {
            get { return "202004032018466_cofig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
